# Generated by Django 6.0.3 on 2026-03-30 17:34

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(db_index=True, help_text='Email address used for login and communications', max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(help_text='The OTP code (can be numeric or alphanumeric depending on type)', max_length=64)),
                ('otp_type', models.CharField(choices=[('email_verification', 'Email Verification'), ('password_reset', 'Password Reset'), ('login', 'Login')], db_index=True, help_text='What this OTP is used for (verification, password reset, etc.)', max_length=30)),
                ('target', models.EmailField(help_text='Target email address (for OTP delivery)', max_length=254)),
                ('is_used', models.BooleanField(db_index=True, default=False, help_text='Whether this OTP has already been consumed')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='OTP expires after this timestamp')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this OTP was created')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address that requested this OTP', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='User agent of the requestor', max_length=500)),
                ('user', models.ForeignKey(help_text='User associated with this OTP', on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'OTPs',
                'db_table': 'otps',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'otp_type', 'is_used'], name='otps_user_id_d6a90f_idx'), models.Index(fields=['target', 'otp_type', 'is_used'], name='otps_target_e79e81_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, help_text="User's first name (optional)", max_length=150)),
                ('last_name', models.CharField(blank=True, help_text="User's last name (optional)", max_length=150)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number in international format (e.g., 233244123456)', max_length=20, null=True)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('blocked', 'Blocked'), ('deactivated', 'Deactivated')], db_index=True, default='active', help_text='Current status of the account', max_length=20)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('operator', 'Operator')], db_index=True, default='customer', help_text='User role for access control', max_length=20)),
                ('is_email_verified', models.BooleanField(default=False, help_text="Whether the user's email has been verified")),
                ('is_phone_verified', models.BooleanField(default=False, help_text="Whether the user's phone number has been verified (future use)")),
                ('failed_login_attempts', models.PositiveSmallIntegerField(default=0, help_text='Consecutive failed login attempts')),
                ('locked_until', models.DateTimeField(blank=True, help_text='Account locked until this timestamp (if locked)', null=True)),
                ('block_reason', models.TextField(blank=True, help_text='Reason for account block (if blocked)', null=True)),
                ('blocked_at', models.DateTimeField(blank=True, help_text='When the account was blocked', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Account creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('blocked_by', models.ForeignKey(blank=True, help_text='Which operator blocked this account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_accounts', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='One-to-one relationship with the User model', on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Account',
                'verbose_name_plural': 'User Accounts',
                'db_table': 'user_accounts',
                'indexes': [models.Index(fields=['account_status', 'role'], name='user_accoun_account_de1c4c_idx'), models.Index(fields=['is_email_verified'], name='user_accoun_is_emai_6e6bc8_idx')],
            },
        ),
    ]
