# Generated by Django 6.0.3 on 2026-03-31 17:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_type', models.CharField(choices=[('shipping', 'Shipping'), ('billing', 'Billing'), ('both', 'Both')], default='shipping', help_text='Type of address: shipping, billing, or both', max_length=10)),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default address for its type')),
                ('recipient_name', models.CharField(help_text='Full name of the recipient', max_length=255)),
                ('phone_number', models.CharField(help_text='Contact phone number for delivery', max_length=20)),
                ('street_address', models.CharField(help_text='House number and street name', max_length=255)),
                ('apartment', models.CharField(blank=True, help_text='Apartment, suite, unit, etc. (optional)', max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - keep for order history')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who owns this address', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'addresses',
                'ordering': ['-is_default', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_deleted'], name='addresses_user_id_13d9ab_idx'), models.Index(fields=['user', 'address_type', 'is_default'], name='addresses_user_id_73d321_idx')],
            },
        ),
    ]
