# Generated by Django 6.0.3 on 2026-03-31 17:40

import apps.orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, default=apps.orders.models.generate_order_number, editable=False, max_length=50, unique=True),
        ),
    ]
