# Generated by Django 6.0.3 on 2026-04-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='customization_images',
            field=models.JSONField(blank=True, default=list, help_text='Array of image URLs for customization (max 4)'),
        ),
    ]
